### ISSUE TITLE
Bug: the link for board of directors is incorrect

### ISSUE THREAD

**Issue by JacobCoffee** [psf/policies#22]
#### What 
 
https://github.com/psf/policies/blob/acab0d819d52e6d2a5acdbb9541beb07b9f7ba96/docs/python.org/code-of-conduct/Procedures-for-Reporting-Incidents.md?plain=1#L30 points to a fellows roster, with the board of directors anchor link no longer existing.

It should probably point to https://www.python.org/psf/board/

**Comment by MrunaliniPachpute** [comment]
I had a solution and will have submitted a PR Sir.
